################################################################################
#
#                  libsegyio Copyright (C) 2021 aoyile
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
################################################################################

INCLUDEPATH += $$PWD/armadillo
DEPENDPATH += $$PWD/armadillo

HEADERS += \
    $$PWD/armadillo/armadillo_bits/access.hpp \
    $$PWD/armadillo/armadillo_bits/arma_cmath.hpp \
    $$PWD/armadillo/armadillo_bits/arma_config.hpp \
    $$PWD/armadillo/armadillo_bits/arma_forward.hpp \
    $$PWD/armadillo/armadillo_bits/arma_ostream_bones.hpp \
    $$PWD/armadillo/armadillo_bits/arma_ostream_meat.hpp \
    $$PWD/armadillo/armadillo_bits/arma_rng.hpp \
    $$PWD/armadillo/armadillo_bits/arma_rng_cxx11.hpp \
    $$PWD/armadillo/armadillo_bits/arma_rng_cxx98.hpp \
    $$PWD/armadillo/armadillo_bits/arma_static_check.hpp \
    $$PWD/armadillo/armadillo_bits/arma_str.hpp \
    $$PWD/armadillo/armadillo_bits/arma_version.hpp \
    $$PWD/armadillo/armadillo_bits/arrayops_bones.hpp \
    $$PWD/armadillo/armadillo_bits/arrayops_meat.hpp \
    $$PWD/armadillo/armadillo_bits/auxlib_bones.hpp \
    $$PWD/armadillo/armadillo_bits/auxlib_meat.hpp \
    $$PWD/armadillo/armadillo_bits/band_helper.hpp \
    $$PWD/armadillo/armadillo_bits/Base_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Base_meat.hpp \
    $$PWD/armadillo/armadillo_bits/BaseCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/BaseCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Col_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Col_meat.hpp \
    $$PWD/armadillo/armadillo_bits/compiler_extra.hpp \
    $$PWD/armadillo/armadillo_bits/compiler_setup.hpp \
    $$PWD/armadillo/armadillo_bits/compiler_setup_post.hpp \
    $$PWD/armadillo/armadillo_bits/cond_rel_bones.hpp \
    $$PWD/armadillo/armadillo_bits/cond_rel_meat.hpp \
    $$PWD/armadillo/armadillo_bits/config.hpp \
    $$PWD/armadillo/armadillo_bits/constants.hpp \
    $$PWD/armadillo/armadillo_bits/constants_old.hpp \
    $$PWD/armadillo/armadillo_bits/Cube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Cube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/debug.hpp \
    $$PWD/armadillo/armadillo_bits/def_arpack.hpp \
    $$PWD/armadillo/armadillo_bits/def_atlas.hpp \
    $$PWD/armadillo/armadillo_bits/def_blas.hpp \
    $$PWD/armadillo/armadillo_bits/def_hdf5.hpp \
    $$PWD/armadillo/armadillo_bits/def_lapack.hpp \
    $$PWD/armadillo/armadillo_bits/def_superlu.hpp \
    $$PWD/armadillo/armadillo_bits/diagmat_proxy.hpp \
    $$PWD/armadillo/armadillo_bits/diagview_bones.hpp \
    $$PWD/armadillo/armadillo_bits/diagview_meat.hpp \
    $$PWD/armadillo/armadillo_bits/diskio_bones.hpp \
    $$PWD/armadillo/armadillo_bits/diskio_meat.hpp \
    $$PWD/armadillo/armadillo_bits/distr_param.hpp \
    $$PWD/armadillo/armadillo_bits/eGlue_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eglue_core_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eglue_core_meat.hpp \
    $$PWD/armadillo/armadillo_bits/eGlue_meat.hpp \
    $$PWD/armadillo/armadillo_bits/eGlueCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eGlueCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/eop_aux.hpp \
    $$PWD/armadillo/armadillo_bits/eOp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eop_core_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eop_core_meat.hpp \
    $$PWD/armadillo/armadillo_bits/eOp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/eOpCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/eOpCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/fft_engine.hpp \
    $$PWD/armadillo/armadillo_bits/field_bones.hpp \
    $$PWD/armadillo/armadillo_bits/field_meat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_accu.hpp \
    $$PWD/armadillo/armadillo_bits/fn_all.hpp \
    $$PWD/armadillo/armadillo_bits/fn_any.hpp \
    $$PWD/armadillo/armadillo_bits/fn_approx_equal.hpp \
    $$PWD/armadillo/armadillo_bits/fn_as_scalar.hpp \
    $$PWD/armadillo/armadillo_bits/fn_chi2rnd.hpp \
    $$PWD/armadillo/armadillo_bits/fn_chol.hpp \
    $$PWD/armadillo/armadillo_bits/fn_clamp.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cond.hpp \
    $$PWD/armadillo/armadillo_bits/fn_conv.hpp \
    $$PWD/armadillo/armadillo_bits/fn_conv_to.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cor.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cov.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cross.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cumprod.hpp \
    $$PWD/armadillo/armadillo_bits/fn_cumsum.hpp \
    $$PWD/armadillo/armadillo_bits/fn_det.hpp \
    $$PWD/armadillo/armadillo_bits/fn_diagmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_diagvec.hpp \
    $$PWD/armadillo/armadillo_bits/fn_diff.hpp \
    $$PWD/armadillo/armadillo_bits/fn_dot.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eig_gen.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eig_pair.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eig_sym.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eigs_gen.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eigs_sym.hpp \
    $$PWD/armadillo/armadillo_bits/fn_elem.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eps.hpp \
    $$PWD/armadillo/armadillo_bits/fn_expmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_eye.hpp \
    $$PWD/armadillo/armadillo_bits/fn_fft.hpp \
    $$PWD/armadillo/armadillo_bits/fn_fft2.hpp \
    $$PWD/armadillo/armadillo_bits/fn_find.hpp \
    $$PWD/armadillo/armadillo_bits/fn_find_unique.hpp \
    $$PWD/armadillo/armadillo_bits/fn_flip.hpp \
    $$PWD/armadillo/armadillo_bits/fn_hess.hpp \
    $$PWD/armadillo/armadillo_bits/fn_hist.hpp \
    $$PWD/armadillo/armadillo_bits/fn_histc.hpp \
    $$PWD/armadillo/armadillo_bits/fn_index_max.hpp \
    $$PWD/armadillo/armadillo_bits/fn_index_min.hpp \
    $$PWD/armadillo/armadillo_bits/fn_inplace_strans.hpp \
    $$PWD/armadillo/armadillo_bits/fn_inplace_trans.hpp \
    $$PWD/armadillo/armadillo_bits/fn_interp1.hpp \
    $$PWD/armadillo/armadillo_bits/fn_intersect.hpp \
    $$PWD/armadillo/armadillo_bits/fn_inv.hpp \
    $$PWD/armadillo/armadillo_bits/fn_join.hpp \
    $$PWD/armadillo/armadillo_bits/fn_kmeans.hpp \
    $$PWD/armadillo/armadillo_bits/fn_kron.hpp \
    $$PWD/armadillo/armadillo_bits/fn_log_det.hpp \
    $$PWD/armadillo/armadillo_bits/fn_logmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_lu.hpp \
    $$PWD/armadillo/armadillo_bits/fn_max.hpp \
    $$PWD/armadillo/armadillo_bits/fn_mean.hpp \
    $$PWD/armadillo/armadillo_bits/fn_median.hpp \
    $$PWD/armadillo/armadillo_bits/fn_min.hpp \
    $$PWD/armadillo/armadillo_bits/fn_misc.hpp \
    $$PWD/armadillo/armadillo_bits/fn_mvnrnd.hpp \
    $$PWD/armadillo/armadillo_bits/fn_n_unique.hpp \
    $$PWD/armadillo/armadillo_bits/fn_nonzeros.hpp \
    $$PWD/armadillo/armadillo_bits/fn_norm.hpp \
    $$PWD/armadillo/armadillo_bits/fn_normalise.hpp \
    $$PWD/armadillo/armadillo_bits/fn_normcdf.hpp \
    $$PWD/armadillo/armadillo_bits/fn_normpdf.hpp \
    $$PWD/armadillo/armadillo_bits/fn_numel.hpp \
    $$PWD/armadillo/armadillo_bits/fn_ones.hpp \
    $$PWD/armadillo/armadillo_bits/fn_orth_null.hpp \
    $$PWD/armadillo/armadillo_bits/fn_pinv.hpp \
    $$PWD/armadillo/armadillo_bits/fn_polyfit.hpp \
    $$PWD/armadillo/armadillo_bits/fn_polyval.hpp \
    $$PWD/armadillo/armadillo_bits/fn_princomp.hpp \
    $$PWD/armadillo/armadillo_bits/fn_prod.hpp \
    $$PWD/armadillo/armadillo_bits/fn_qr.hpp \
    $$PWD/armadillo/armadillo_bits/fn_qz.hpp \
    $$PWD/armadillo/armadillo_bits/fn_randg.hpp \
    $$PWD/armadillo/armadillo_bits/fn_randi.hpp \
    $$PWD/armadillo/armadillo_bits/fn_randn.hpp \
    $$PWD/armadillo/armadillo_bits/fn_randu.hpp \
    $$PWD/armadillo/armadillo_bits/fn_range.hpp \
    $$PWD/armadillo/armadillo_bits/fn_rank.hpp \
    $$PWD/armadillo/armadillo_bits/fn_regspace.hpp \
    $$PWD/armadillo/armadillo_bits/fn_repelem.hpp \
    $$PWD/armadillo/armadillo_bits/fn_repmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_reshape.hpp \
    $$PWD/armadillo/armadillo_bits/fn_resize.hpp \
    $$PWD/armadillo/armadillo_bits/fn_reverse.hpp \
    $$PWD/armadillo/armadillo_bits/fn_roots.hpp \
    $$PWD/armadillo/armadillo_bits/fn_schur.hpp \
    $$PWD/armadillo/armadillo_bits/fn_shift.hpp \
    $$PWD/armadillo/armadillo_bits/fn_shuffle.hpp \
    $$PWD/armadillo/armadillo_bits/fn_size.hpp \
    $$PWD/armadillo/armadillo_bits/fn_solve.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sort.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sort_index.hpp \
    $$PWD/armadillo/armadillo_bits/fn_speye.hpp \
    $$PWD/armadillo/armadillo_bits/fn_spones.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sprandn.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sprandu.hpp \
    $$PWD/armadillo/armadillo_bits/fn_spsolve.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sqrtmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_stddev.hpp \
    $$PWD/armadillo/armadillo_bits/fn_strans.hpp \
    $$PWD/armadillo/armadillo_bits/fn_sum.hpp \
    $$PWD/armadillo/armadillo_bits/fn_svd.hpp \
    $$PWD/armadillo/armadillo_bits/fn_svds.hpp \
    $$PWD/armadillo/armadillo_bits/fn_syl_lyap.hpp \
    $$PWD/armadillo/armadillo_bits/fn_symmat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_toeplitz.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trace.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trans.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trapz.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trig.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trimat.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trunc_exp.hpp \
    $$PWD/armadillo/armadillo_bits/fn_trunc_log.hpp \
    $$PWD/armadillo/armadillo_bits/fn_unique.hpp \
    $$PWD/armadillo/armadillo_bits/fn_var.hpp \
    $$PWD/armadillo/armadillo_bits/fn_vectorise.hpp \
    $$PWD/armadillo/armadillo_bits/fn_wishrnd.hpp \
    $$PWD/armadillo/armadillo_bits/fn_zeros.hpp \
    $$PWD/armadillo/armadillo_bits/Gen_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Gen_meat.hpp \
    $$PWD/armadillo/armadillo_bits/GenCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/GenCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/GenSpecialiser.hpp \
    $$PWD/armadillo/armadillo_bits/glue_affmul_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_affmul_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_atan2_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_atan2_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Glue_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_conv_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_conv_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cor_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cor_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cov_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cov_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cross_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_cross_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_hist_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_hist_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_histc_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_histc_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_hypot_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_hypot_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_intersect_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_intersect_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_join_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_join_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_kron_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_kron_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_max_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_max_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Glue_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_min_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_min_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_mixed_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_mixed_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_mvnrnd_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_mvnrnd_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_polyfit_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_polyfit_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_polyval_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_polyval_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_relational_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_relational_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_solve_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_solve_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_times_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_times_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_toeplitz_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_toeplitz_meat.hpp \
    $$PWD/armadillo/armadillo_bits/glue_trapz_bones.hpp \
    $$PWD/armadillo/armadillo_bits/glue_trapz_meat.hpp \
    $$PWD/armadillo/armadillo_bits/GlueCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/GlueCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_diag_bones.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_diag_meat.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_full_bones.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_full_meat.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_misc_bones.hpp \
    $$PWD/armadillo/armadillo_bits/gmm_misc_meat.hpp \
    $$PWD/armadillo/armadillo_bits/hdf5_misc.hpp \
    $$PWD/armadillo/armadillo_bits/include_atlas.hpp \
    $$PWD/armadillo/armadillo_bits/include_hdf5.hpp \
    $$PWD/armadillo/armadillo_bits/include_superlu.hpp \
    $$PWD/armadillo/armadillo_bits/injector_bones.hpp \
    $$PWD/armadillo/armadillo_bits/injector_meat.hpp \
    $$PWD/armadillo/armadillo_bits/MapMat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/MapMat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Mat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Mat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/memory.hpp \
    $$PWD/armadillo/armadillo_bits/mp_misc.hpp \
    $$PWD/armadillo/armadillo_bits/mtGlue_bones.hpp \
    $$PWD/armadillo/armadillo_bits/mtGlue_meat.hpp \
    $$PWD/armadillo/armadillo_bits/mtGlueCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/mtGlueCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/mtOp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/mtOp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/mtOpCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/mtOpCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/mtSpOp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/mtSpOp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/mul_gemm.hpp \
    $$PWD/armadillo/armadillo_bits/mul_gemm_mixed.hpp \
    $$PWD/armadillo/armadillo_bits/mul_gemv.hpp \
    $$PWD/armadillo/armadillo_bits/mul_herk.hpp \
    $$PWD/armadillo/armadillo_bits/mul_syrk.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_cx_attrib.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_DenseGenMatProd_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_DenseGenMatProd_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_DoubleShiftQR_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_DoubleShiftQR_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_EigsSelect.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_GenEigsSolver_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_GenEigsSolver_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_SortEigenvalue.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_SparseGenMatProd_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_SparseGenMatProd_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_SymEigsSolver_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_SymEigsSolver_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_TridiagEigen_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_TridiagEigen_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_UpperHessenbergEigen_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_UpperHessenbergEigen_meat.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_UpperHessenbergQR_bones.hpp \
    $$PWD/armadillo/armadillo_bits/newarp_UpperHessenbergQR_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_all_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_all_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_any_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_any_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Op_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_chi2rnd_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_chi2rnd_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_chol_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_chol_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_clamp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_clamp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cond_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cond_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cor_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cor_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cov_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cov_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cumprod_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cumprod_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cumsum_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cumsum_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_cx_scalar_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_cx_scalar_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_diagmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_diagmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_diagvec_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_diagvec_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_diff_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_diff_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_dot_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_dot_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_dotext_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_dotext_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_expmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_expmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_fft_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_fft_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_find_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_find_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_find_unique_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_find_unique_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_flip_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_flip_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_hist_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_hist_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_htrans_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_htrans_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_index_max_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_index_max_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_index_min_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_index_min_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_inv_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_inv_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_logmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_logmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_max_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_max_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_mean_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_mean_meat.hpp \
    $$PWD/armadillo/armadillo_bits/Op_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_median_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_median_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_min_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_min_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_misc_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_misc_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_nonzeros_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_nonzeros_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_norm_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_norm_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_normalise_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_normalise_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_orth_null_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_orth_null_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_pinv_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_pinv_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_princomp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_princomp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_prod_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_prod_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_range_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_range_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_relational_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_relational_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_repelem_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_repelem_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_repmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_repmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_reshape_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_reshape_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_resize_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_resize_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_reverse_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_reverse_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_roots_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_roots_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_shift_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_shift_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_shuffle_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_shuffle_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_sort_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_sort_index_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_sort_index_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_sort_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_sqrtmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_sqrtmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_stddev_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_stddev_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_strans_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_strans_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_sum_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_sum_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_symmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_symmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_toeplitz_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_toeplitz_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_trimat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_trimat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_unique_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_unique_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_var_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_var_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_vectorise_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_vectorise_meat.hpp \
    $$PWD/armadillo/armadillo_bits/op_wishrnd_bones.hpp \
    $$PWD/armadillo/armadillo_bits/op_wishrnd_meat.hpp \
    $$PWD/armadillo/armadillo_bits/OpCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/OpCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_div.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_minus.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_plus.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_relational.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_schur.hpp \
    $$PWD/armadillo/armadillo_bits/operator_cube_times.hpp \
    $$PWD/armadillo/armadillo_bits/operator_div.hpp \
    $$PWD/armadillo/armadillo_bits/operator_minus.hpp \
    $$PWD/armadillo/armadillo_bits/operator_ostream.hpp \
    $$PWD/armadillo/armadillo_bits/operator_plus.hpp \
    $$PWD/armadillo/armadillo_bits/operator_relational.hpp \
    $$PWD/armadillo/armadillo_bits/operator_schur.hpp \
    $$PWD/armadillo/armadillo_bits/operator_times.hpp \
    $$PWD/armadillo/armadillo_bits/podarray_bones.hpp \
    $$PWD/armadillo/armadillo_bits/podarray_meat.hpp \
    $$PWD/armadillo/armadillo_bits/promote_type.hpp \
    $$PWD/armadillo/armadillo_bits/Proxy.hpp \
    $$PWD/armadillo/armadillo_bits/ProxyCube.hpp \
    $$PWD/armadillo/armadillo_bits/restrictors.hpp \
    $$PWD/armadillo/armadillo_bits/Row_bones.hpp \
    $$PWD/armadillo/armadillo_bits/Row_meat.hpp \
    $$PWD/armadillo/armadillo_bits/running_stat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/running_stat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/running_stat_vec_bones.hpp \
    $$PWD/armadillo/armadillo_bits/running_stat_vec_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SizeCube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SizeCube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SizeMat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SizeMat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/sp_auxlib_bones.hpp \
    $$PWD/armadillo/armadillo_bits/sp_auxlib_meat.hpp \
    $$PWD/armadillo/armadillo_bits/span.hpp \
    $$PWD/armadillo/armadillo_bits/SpBase_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpBase_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpCol_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpCol_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spdiagview_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spdiagview_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpGlue_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_elem_helper_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_elem_helper_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_join_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_join_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_kron_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_kron_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpGlue_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_minus_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_minus_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_plus_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_plus_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_schur_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_schur_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_times_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spglue_times_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpMat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpMat_iterators_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpMat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpOp_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_diagmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_diagmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_htrans_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_htrans_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_max_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_max_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_mean_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_mean_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpOp_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_min_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_min_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_misc_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_misc_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_normalise_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_normalise_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_repmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_repmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_reverse_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_reverse_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_strans_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_strans_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_sum_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_sum_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_symmat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_symmat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_trimat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_trimat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/spop_var_bones.hpp \
    $$PWD/armadillo/armadillo_bits/spop_var_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpProxy.hpp \
    $$PWD/armadillo/armadillo_bits/SpRow_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpRow_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpSubview_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpSubview_iterators_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpSubview_meat.hpp \
    $$PWD/armadillo/armadillo_bits/SpValProxy_bones.hpp \
    $$PWD/armadillo/armadillo_bits/SpValProxy_meat.hpp \
    $$PWD/armadillo/armadillo_bits/strip.hpp \
    $$PWD/armadillo/armadillo_bits/subview_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_each_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_each_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_slices_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_cube_slices_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_each_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_each_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_elem1_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_elem1_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_elem2_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_elem2_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_field_bones.hpp \
    $$PWD/armadillo/armadillo_bits/subview_field_meat.hpp \
    $$PWD/armadillo/armadillo_bits/subview_meat.hpp \
    $$PWD/armadillo/armadillo_bits/sympd_helper.hpp \
    $$PWD/armadillo/armadillo_bits/traits.hpp \
    $$PWD/armadillo/armadillo_bits/typedef_elem.hpp \
    $$PWD/armadillo/armadillo_bits/typedef_elem_check.hpp \
    $$PWD/armadillo/armadillo_bits/typedef_mat.hpp \
    $$PWD/armadillo/armadillo_bits/typedef_mat_fixed.hpp \
    $$PWD/armadillo/armadillo_bits/unwrap.hpp \
    $$PWD/armadillo/armadillo_bits/unwrap_cube.hpp \
    $$PWD/armadillo/armadillo_bits/unwrap_spmat.hpp \
    $$PWD/armadillo/armadillo_bits/upgrade_val.hpp \
    $$PWD/armadillo/armadillo_bits/wall_clock_bones.hpp \
    $$PWD/armadillo/armadillo_bits/wall_clock_meat.hpp \
    $$PWD/armadillo/armadillo_bits/wrapper_arpack.hpp \
    $$PWD/armadillo/armadillo_bits/wrapper_atlas.hpp \
    $$PWD/armadillo/armadillo_bits/wrapper_blas.hpp \
    $$PWD/armadillo/armadillo_bits/wrapper_lapack.hpp \
    $$PWD/armadillo/armadillo_bits/wrapper_superlu.hpp \
    $$PWD/armadillo/armadillo_bits/xtrans_mat_bones.hpp \
    $$PWD/armadillo/armadillo_bits/xtrans_mat_meat.hpp \
    $$PWD/armadillo/armadillo_bits/xvec_htrans_bones.hpp \
    $$PWD/armadillo/armadillo_bits/xvec_htrans_meat.hpp \
    $$PWD/armadillo/armadillo
